### ISSUE TITLE
A resume about performance and internals

### ISSUE THREAD

**Issue by sveetch** [pyshare/datalookup#10]
Your project is interesting but actually i don't really know where it would fit in various projects. 

What about the performance ? I imagine this won't be a solution at least for large dataset that could replace a SGDB but it would be nice to make a point on this into your introduction.

Also a short resume about how i works internally to perform queries on dataset would help to make an idea about possible usages.

Thanks.

**Comment by StephaneCapponi** [comment]
Hi @sveetch, 

Thanks for your comments.

To answer your first question. I can give you a brief example on how I use it in one of my framework. 
I have a set of applications that I need to build for an embedded platform. Something iike:

```
[
    {
        "name": "app1"
        "group": [
            "group1",
            "group2"
        ]
    },
    {
        "name": "app2"
        "group": [
            "group1",
        ]
    },
    {
        "name": "app3"
        "group": [
            "group3"
        ]
    }
]
```

This is a simplified version, but it allow me then to filter what I exactly need to build. I can build only application that are part of the "group1" or with the name "app1" etc...

---

Performance is a good topic, I would also be interested in benchmarking the library to see how fast we can be on a big json file and big request that needs to be filtered. That is something I can work on.

---

Last point, I can make a internal documentation for people that want's to contribute for the project. However I don't understand what you mean by "would help to make an idea about possible usages". Possible usages for new features ? Or possible usage for current inplemenation ?

**Comment by sveetch** [comment]
I was talking about a possible use-case it could fill in various projects.  I don't think you need a proper document for this, just a resume which explain quickly this is only about to query a dataset with just some Python builtins. 

Like you said in README you are filtering but do you maintain an internal index in memory or something alike ?

I did some very quick review in your code and it seems you are using Node object to get a quick way to the dataset items ?

**Comment by StephaneCapponi** [comment]
I take your first point.

I do not maintain an internal index in memory. It would take to much resource and I don't believe it is necessary. What I do and as you mentioned in your comment. I convert every dictionary as a Node. A Node is a simple class that convert key and value to Field attribute that allow me to know with what kind of data I'm dealing with. 

Each field of a node has its own lookups to be able to match for a specific data. At the end what the filter function does is calling each lookup of each field using the given filters.

A Dataset is like a Node registry. The filter function or other function of the Dataset often refer to a function of a Node.

I believe the library is pretty fast on big data as I don't do much computation. But this needs to be bencmarked. 

I hope I answered correctly your question. Otherwise do not hesitate to reiterate i would be glad to help understanding the library better.

Also, if you have any suggestion on how to make it better or faster, do not hesitate to open a ticket or contribute to the project!

**Comment by sveetch** [comment]
Well it's a great explanation, thank you. Hope to use it soon for a new project to come. Feel free to close this issue when you want, cheers
